[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.31"
local-ip-address = "0.5"
network-interface = "1.1"
ipnet = "2"
ipconfig = "0.3"
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
